"""change position table to use geometry

Revision ID: 96e3651e8705
Revises: 
Create Date: 2020-12-11 09:50:01.155852

"""
import sqlalchemy as sa
from alembic import op
# revision identifiers, used by Alembic.
from geoalchemy2 import Geometry

revision = '96e3651e8705'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operator',
                    sa.Column('mcc_mnc', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=64), nullable=False),
                    sa.PrimaryKeyConstraint('mcc_mnc')
                    )
    op.create_index(op.f('ix_operator_name'), 'operator', ['name'], unique=False)
    op.create_table('position',
                    sa.Column('location', Geometry(geometry_type='POINT', srid=4326), nullable=False),
                    sa.Column('operator_code', sa.Integer(), nullable=False),
                    sa.Column('has_2g', sa.Boolean(), nullable=True),
                    sa.Column('has_3g', sa.Boolean(), nullable=True),
                    sa.Column('has_4g', sa.Boolean(), nullable=True),
                    sa.ForeignKeyConstraint(['operator_code'], ['operator.mcc_mnc'], ),
                    sa.PrimaryKeyConstraint('location', 'operator_code')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('position')
    op.drop_index(op.f('ix_operator_name'), table_name='operator')
    op.drop_table('operator')
    # ### end Alembic commands ###
